language: java
jdk: oraclejdk8
install: true
script: "./build-and-deploy-if-version-tag.sh"
deploy:
  provider: releases
  api_key:
    secure: XG/7aD4q1xgKZP+sBKmbSFS/Ndz7XhgOuUzQOq+juDfJi0yn2DyBYl4wmkprUBXrzBMeZDkdloq/Q12dLRAkB1bCIxQEgQSctXK8wcoB2szjuuy/G8/Nq4TJ2nvGoyJD5FiX+/wHDYiMX4rIsrRcrWmih8BCbtZSBF6b+8yN42U=
  file_glob: true
  file: target/org.moreunit.intellij.plugin-*.jar
  skip_cleanup: true
  on:
    repo: MoreUnit/org.moreunit.intellij.plugin
    tags: true
    condition: -n "$(git tag -l --contains HEAD | grep -E '^v[0-9]+\.[0-9]+\.[0-9]+')"
env:
  global:
  - secure: dgDLZ3447vHIRHydEYh9u59i5OnUXbzYaj1hEJqHls6aDLd/riIvMUfZAyzJtqJ8xCbAym8ZG1XH6jXLn4IPqkE3pNCgA2VfNqbw0gEAt8S+CJHyBH1twPZfHEYi074ast4mMdnb4QEND+js+cqGFRCgitFi6hHjPev6kxmXZQQ=
  - secure: QOkzMriv1RhFsfKX6H5pjDQibufj9eCTBFbwUp+8XN4qjRfvxJwPIFJFd18/LlZ8hFbr9tvWJ1vih73NFR62csflPYKboNbcJag898bv82rcK9hgLCUgqEntD9xesM3yTM2Kg42QUi5R3oZ4z1qA5rQUqRK9BhQg6/H6DCHSIXQ=
