language: java
jdk: openjdk6
install: true
script: ./build.sh
deploy:
  provider: releases
  api_key:
    secure: XG/7aD4q1xgKZP+sBKmbSFS/Ndz7XhgOuUzQOq+juDfJi0yn2DyBYl4wmkprUBXrzBMeZDkdloq/Q12dLRAkB1bCIxQEgQSctXK8wcoB2szjuuy/G8/Nq4TJ2nvGoyJD5FiX+/wHDYiMX4rIsrRcrWmih8BCbtZSBF6b+8yN42U=
  file_glob: true
  file: target/org.moreunit.intellij.plugin-*.jar
  skip_cleanup: true
  on:
    repo: MoreUnit/org.moreunit.intellij.plugin
    tags: true
    condition: -n "$(git tag -l --contains HEAD | grep -E '^v[0-9]+\.[0-9]+\.[0-9]+')"
